-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 16:21:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_bicycle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_bicycle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_bicycle` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_bicycle` ;

-- -----------------------------------------------------
-- Table `db_bicycle`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bicycle`.`Member` (
  `id` VARCHAR(11) NOT NULL,
  `fname` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `address` VARCHAR(512) NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bicycle`.`Parking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bicycle`.`Parking` (
  `id` VARCHAR(11) NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bicycle`.`Bicycle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bicycle`.`Bicycle` (
  `id` VARCHAR(11) NOT NULL,
  `parking_id` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_park_bi_idx` (`parking_id` ASC) VISIBLE,
  CONSTRAINT `fk_park_bi`
    FOREIGN KEY (`parking_id`)
    REFERENCES `db_bicycle`.`Parking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bicycle`.`Rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bicycle`.`Rental` (
  `id` VARCHAR(11) NOT NULL,
  `bicycle_id` VARCHAR(11) NULL,
  `member_id` VARCHAR(11) NULL,
  `start_date` DATETIME NULL,
  `start_statn` VARCHAR(11) NULL,
  `end_date` DATETIME NULL,
  `end_statn` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bi_ren_idx` (`bicycle_id` ASC) VISIBLE,
  INDEX `fk_mem_ren_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_start_ren_idx` (`start_statn` ASC) VISIBLE,
  INDEX `fk_end_ren_idx` (`end_statn` ASC) VISIBLE,
  CONSTRAINT `fk_bi_ren`
    FOREIGN KEY (`bicycle_id`)
    REFERENCES `db_bicycle`.`Bicycle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mem_ren`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_bicycle`.`Member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_start_ren`
    FOREIGN KEY (`start_statn`)
    REFERENCES `db_bicycle`.`Parking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_end_ren`
    FOREIGN KEY (`end_statn`)
    REFERENCES `db_bicycle`.`Parking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `db_bicycle`.`parking` (`id`, `name`) VALUES ('p01', 'คอมเพล็กซ์');
INSERT INTO `db_bicycle`.`parking` (`id`, `name`) VALUES ('p02', 'หอพัก 9 หลัง');
INSERT INTO `db_bicycle`.`parking` (`id`, `name`) VALUES ('p03', 'กังสดาล');